spring.application.name=demo
spring.datasource.url=jdbc:postgresql://db.btiwwugnnfgtgnhtwegn.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=89hnAhEVc91Cp8qH
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
supabase.url=${SUPABASE_URL}
supabase.anon.key=${SUPABASE_ANON_KEY}
supabase.service.role=${SUPABASE_SERVICE_ROLE_KEY}
